mode: "image"  # or "video"

video:
  video_path: "data/my_video.mp4"
  frame_sampling:
    method: "scene"
    params:
      threshold: 30.0

image:
  image_path: "/Users/andrewdelacruz/e2e_sam2/data/thor_hammer.jpeg"

segmentation:
  queries: ["hammer"]
  detection_threshold: 0.1
  segmentation_threshold: 0.5
  results_dir: "results"

embedding:
  model_types: ["clip"]
  device: "cuda"

serialization:
  output_json: "results/crop_embeddings.json" 