models:
  clip:
    model_name: "ViT-B/32"
    threshold: 0.75
  vit:
    model_name: "vit_base_patch16_224"
    threshold: 0.75
  resnet50:
    model_name: "resnet50"
    threshold: 0.75

detection:
  min_confidence: 0.5
  nms_threshold: 0.45

output:
  save_visualizations: true
  save_embeddings: true
  metrics_report: true
  
device: "cpu"  # can be "cuda", "mps", or "cpu" 